name: Lint, Test and Deploy
on: push
jobs:
  pull-code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Lint Code
        run: npm run lint
      - name: Test Code 
        run: npm run test
  
  deploy:
    needs: pull-code
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Deploy Code
        run: echo "Code, Deployed"